/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package holon;

import holon.Mass;
import org.junit.Test;
import static org.junit.Assert.*;

public class MassTest {
    @Test public void testFromAndToGrams() {
    	Mass m = Mass.fromGrams(100.5);
    	assertEquals(100.5, m.grams(), .01);
    }
    @Test public void testFromAndToKilograms() {
    	Mass m = Mass.fromKilograms(100.5);
    	assertEquals(100.5, m.kilograms(), .01);
    }
    
    @Test public void testConvertPrefix() {
    	Mass m = Mass.fromKilograms(100.5);
    	assertEquals(100500, m.grams(), .01);
    }
}
